<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 public/models/PrivatePlaneInterior.glb -T -d /draco
-->

<script lang="ts">
  import { T } from "@threlte/core";
  import { interactivity, useGltf } from "@threlte/extras";
  import { useSequence } from "@threlte/theatre";
  import { Group } from "three";
  import { DRACOLoader } from "three/examples/jsm/loaders/DRACOLoader.js";

  const { play } = useSequence();

  interactivity();

  export const ref = new Group();
  export let position: [number, number, number] = [0, 0, 0];

  const dracoLoader = new DRACOLoader();
  dracoLoader.setDecoderPath("/draco/");

  const gltf = useGltf(
    "/vite-dev/models/PrivatePlaneInterior-transformed.glb",
    {
      dracoLoader,
    }
  );
</script>

<T is={ref} dispose={false} {...$$restProps} useDraco="/draco/">
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group
      rotation={[0, Math.PI / 2, 0]}
      {position}
      onpointerdown={() => {
        play();
      }}
    >
      <T.Mesh
        geometry={gltf.nodes.kitchen_wall_01_1001.geometry}
        material={gltf.materials.mat_kitchen_wall_01_1001}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.kitchen_wall_02_1001.geometry}
        material={gltf.materials.mat_kitchen_wall_01_1001}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.kitchen_wall_03_1001.geometry}
        material={gltf.materials.mat_kitchen_wall_01_1001}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.kitchen_wall_04_1001.geometry}
        material={gltf.materials.mat_kitchen_wall_01_1001}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.kitchen_wall_05_1001.geometry}
        material={gltf.materials.mat_Glass}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.kitchen_wall_06_1001.geometry}
        material={gltf.materials.mat_Glass}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.Flooring_1002.geometry}
        material={gltf.materials.mat_Flooring_1002}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.fuselage_walls_L_1003.geometry}
        material={gltf.materials.mat_fuselage_walls_1003}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.fuselage_walls_R_1003.geometry}
        material={gltf.materials.mat_fuselage_walls_1003}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.Portholes_R_1003.geometry}
        material={gltf.materials.mat_fuselage_walls_1003}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.Portholes_L_1003.geometry}
        material={gltf.materials.mat_fuselage_walls_1003}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.Ceiling_1003.geometry}
        material={gltf.materials.mat_fuselage_walls_1003}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.Wall_panel_R_1004.geometry}
        material={gltf.materials.mat_Wall_panel_R_1004}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.Wall_panel_L_1004.geometry}
        material={gltf.materials.mat_Wall_panel_R_1004}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.table_01_1004.geometry}
        material={gltf.materials.mat_Wall_panel_R_1004}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.table_02_1004.geometry}
        material={gltf.materials.mat_Wall_panel_R_1004}
        position={[2.45, 0, -1.49]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.table_03_1004.geometry}
        material={gltf.materials.mat_Wall_panel_R_1004}
        position={[0, 0, -1.49]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.Partial_fuselage_1005.geometry}
        material={gltf.materials.mat_Plane_1005}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.armchair_1006_01.geometry}
        material={gltf.materials.mat_armchair_1006}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.armchair_1006_02.geometry}
        material={gltf.materials.mat_armchair_1006}
        position={[2.45, 0, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.armchair_1006_04.geometry}
        material={gltf.materials.mat_armchair_1006}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.armchair_1006_03.geometry}
        material={gltf.materials.mat_armchair_1006}
        position={[2.45, 0, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.armchair_1006_05.geometry}
        material={gltf.materials.mat_armchair_1006}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.armchair_1006_06.geometry}
        material={gltf.materials.mat_armchair_1006}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.sofa_1007.geometry}
        material={gltf.materials.mat_sofa_1007}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
