<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 PrivatePlaneInteriorWorking.glb
-->

<script>
  import { T } from "@threlte/core";
  import * as THREE from "three";
  import { interactivity, useCursor, useGltf } from "@threlte/extras";
  import { DRACOLoader } from "three/examples/jsm/loaders/DRACOLoader.js";

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    position,
    ...props
  } = $props();

  interactivity();
  const { onPointerEnter, onPointerLeave } = useCursor();

  const dracoLoader = new DRACOLoader();
  dracoLoader.setDecoderPath("/draco/");
  const gltf = useGltf("/vite-dev/models/PrivatePlaneInteriorWorking.glb", {
    dracoLoader,
  });
  const notHoveringColor = "#ffffff";
  const hoveringColor = "#fec900";
  let color = $state(notHoveringColor);
</script>

<T.Group bind:ref dispose={false} {...props} useDraco="/draco/">
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group rotation={[0, Math.PI / 2, 0]} {position}>
      <T.Mesh
        geometry={gltf.nodes.kitchen_wall_01_1001.geometry}
        material={gltf.materials.mat_kitchen_wall_01_1001}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.kitchen_wall_02_1001.geometry}
        material={gltf.materials.mat_kitchen_wall_01_1001}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.kitchen_wall_03_1001.geometry}
        material={gltf.materials.mat_kitchen_wall_01_1001}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.kitchen_wall_04_1001.geometry}
        material={gltf.materials.mat_kitchen_wall_01_1001}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.kitchen_wall_05_1001.geometry}
        material={gltf.materials.mat_Glass}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.kitchen_wall_06_1001.geometry}
        material={gltf.materials.mat_Glass}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.Flooring_1002.geometry}
        material={gltf.materials.mat_Flooring_1002}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.fuselage_walls_L_1003.geometry}
        material={gltf.materials.mat_fuselage_walls_1003}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.fuselage_walls_R_1003.geometry}
        material={gltf.materials.mat_fuselage_walls_1003}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.Portholes_R_1003.geometry}
        material={gltf.materials.mat_fuselage_walls_1003}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.Portholes_L_1003.geometry}
        material={gltf.materials.mat_fuselage_walls_1003}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.Ceiling_1003.geometry}
        material={gltf.materials.mat_fuselage_walls_1003}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.Wall_panel_R_1004.geometry}
        material={gltf.materials.mat_Wall_panel_R_1004}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.Wall_panel_L_1004.geometry}
        material={gltf.materials.mat_Wall_panel_R_1004}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.table_01_1004.geometry}
        material={gltf.materials.mat_Wall_panel_R_1004}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.table_02_1004.geometry}
        material={gltf.materials.mat_Wall_panel_R_1004}
        position={[2.45, 0, -1.49]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.table_03_1004.geometry}
        material={gltf.materials.mat_Wall_panel_R_1004}
        position={[0, 0, -1.49]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.Partial_fuselage_1005.geometry}
        material={gltf.materials.mat_Plane_1005}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.armchair_1006_01.geometry}
        material={gltf.materials.mat_armchair_1006}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.armchair_1006_02.geometry}
        material={gltf.materials.mat_armchair_1006}
        position={[2.45, 0, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.armchair_1006_03.geometry}
        material={gltf.materials.mat_armchair_1006}
        position={[2.45, 0, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.armchair_1006_04.geometry}
        material={gltf.materials.mat_armchair_1006}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.armchair_1006_05.geometry}
        material={gltf.materials.mat_armchair_1006}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.armchair_1006_06.geometry}
        material={gltf.materials.mat_armchair_1006}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={-0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.sofa_1007.geometry}
        material={gltf.materials.mat_sofa_1007}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane.geometry}
        material={gltf.nodes.Plane.material}
        position={[0, -1.2, 0]}
        scale={[3.95, 7.65, 1.64]}
      />
      <T.Mesh
        geometry={new THREE.BoxGeometry(0.625, 0.001, 0.5)}
        position={[-1.05, -0.58, 0.52]}
        rotation={[0, 0.56, 0]}
        scale={[0.28, 1.49, 0.2]}
        onpointerenter={() => {
          onPointerEnter();
          color = hoveringColor;
        }}
        onpointerleave={() => {
          onPointerLeave();
          color = notHoveringColor;
        }}
      >
        <T.MeshStandardMaterial {color} /></T.Mesh
      >
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
